name: CI/CD Localhost

on:
  push:
    branches: ["main"]

jobs:
  deploy-local:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Docker Login
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Run
        run: |
          # Build image
          docker build -t khanhtaitran/my-app:latest .

          docker push khanhtaitran/my-app:latest

          docker stop my-app || true
          docker rm my-app || true
          docker run -d --name my-app -p 80:8080 khanhtaitran/my-app:latest
